### ISSUE TITLE
Test failed on dweather client

### ISSUE THREAD

**Issue by bm777** [dClimate/dWeather-Python-Client#32]
Hi,

- I cloned the repo as well. And the package work very well. 
- And ipfs installation worked too (I succeed to see peers http://127.0.0.1:5001/webui).
- Internet connexion is good :)

But when I run, `python -m pytest -s --log-cli-level=20 dweather_client/tests`, gaev 9 passed and 11 failed.
 
Does it imply that My client could not work when I will integrate it into my main program? 
There is some way to solve it?

![fail](https://user-images.githubusercontent.com/29865600/124374443-1543cc00-dc93-11eb-91db-7a5714329e93.png)

**Comment by sunburntcat** [comment]
First thing to check would be which Python version you are using. Could you provide it?

$python --version

**Comment by bm777** [comment]
Python 3
